module.exports.config = {
  name: "img",
  des: "Image From Text Generated By Open AI",
  nodeDepends: {},
  author: "John Arida",
  version: "1.0.0",
  perm: 0
};

module.exports.start = async function({ event, api }) {
  const msg = global.msg;
  if (!msg)
    return api.sendMessage(global.langText("commands", "noText"), event.threadID, event.messageID);
  api.sendMessage("Searching... 🔎", event.threadID, event.messageID);
  const request = require("request");
  const fs = require("fs-extra");
  try {
    const { Configuration, OpenAIApi } = require("openai");
    const configuration = new Configuration({
      apiKey: global.config.openai,
    });
    const openai = new OpenAIApi(configuration);
    const response = await openai.createImage({
      prompt: msg,
      n: 2,
      size: "1024x1024",
    });
    var data = response.data.data[0].url;
    var callback = () => api.sendMessage(
      { body: ``, attachment: fs.createReadStream(__dirname + "/cache/1.png") }, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.png"));
    return request(data).pipe(fs.createWriteStream(__dirname + '/cache/1.png')).on('close', () => callback());
  } catch (e) {
    return api.sendMessage(global.langText("commands", "err", e), event.threadID, event.messageID)
  }
}